# Generated by Django 4.2.25 on 2025-10-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
